feat(author-jinja): Load jinja extensions from plugins
oscal-compass/compliance-trestle pull request #1710
Opened 2024-09-25 15:27 UTC by rahearn

## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

Builds on the proof of concept at #1684 and:

* moves the methods in the previously new `ssp_interface` into a set of jinja filters. Example switch in use:

`{% for party in ssp_interface.get_parties_for_role(ssp.metadata.responsible_parties, "prepared-by") %}` becomes
`{% for party in ssp.metadata.responsible_parties | parties_for_role("prepared-by", ssp) %}`

`{{ ssp_interface.safe_retrieval(address, 'addr_lines', []) | join(' ') }}` becomes `{{ address.addr_lines | as_list | join(' ') }}`

* refactors the jinja code into a module to better organize it and avoid some circular dependencies
* enables loading extensions from plugins, searching under: `trestle_{plugin_name}.jinja_ext`
* updates plugin docs

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

2024-10-02 12:46 UTC, butler54 commented
Hi @rahearn  - sorry for the delay. I'll look at this in the next few days :).

2024-10-08 16:24 UTC, jpower432 requested changes
@rahearn Thanks for this submission! Wanted to add some early feedback here. Requesting new source code files (the newly created `jinja` package in this case) have the updated copyright info. I added a suggestion on one of the files to what this should be updated to.

2024-10-08 16:24 UTC, jpower432 commented on tests/trestle/core/jinja/filters_test.py
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
```suggestion
# Copyright (c) 2024 The OSCAL Compass Authors.
```

2024-10-19 04:13 UTC, butler54 approved these changes
LGTM - This is really great work.  @jpower432's picked up one comment otherwise the only thing that i've seen here which needs to be tidied here is a dangling comment.

2024-10-19 04:13 UTC, butler54 commented on trestle/core/plugins.py
> +def discovered_plugins(search_module: str) -> Iterator[Tuple[str, Any]]:
This is a nice improvement :)

2024-10-19 04:13 UTC, butler54 commented on trestle/core/jinja/base.py
> +    # This
Think `#this` needs to be cleaned up.

2024-10-21 12:53 UTC, jpower432 approved these changes
LGTM. Thanks for the contribution @rahearn!

2024-10-22 15:45 UTC, jpower432 commented
@rahearn Your branch needs to be up to date with the base branch and then it should be good to merge.

2024-10-22 16:02 UTC, merged